/*
 * Criativei API
 *
 * API responsible for managing the distribution of images in their folders 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: agoisrj@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = criativei_server.Client.OpenAPIDateConverter;
using System.Reflection;

namespace criativei_server.Model
{
    /// <summary>
    /// NewUsers207ResponseInner
    /// </summary>
    [JsonConverter(typeof(NewUsers207ResponseInnerJsonConverter))]
    [DataContract(Name = "new_users_207_response_inner")]
    public partial class NewUsers207ResponseInner : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NewUsers207ResponseInner" /> class
        /// with the <see cref="UserModel" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of UserModel.</param>
        public NewUsers207ResponseInner(UserModel actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NewUsers207ResponseInner" /> class
        /// with the <see cref="CustomStatus" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CustomStatus.</param>
        public NewUsers207ResponseInner(CustomStatus actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(CustomStatus))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(UserModel))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: CustomStatus, UserModel");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `UserModel`. If the actual instance is not `UserModel`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of UserModel</returns>
        public UserModel GetUserModel()
        {
            return (UserModel)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `CustomStatus`. If the actual instance is not `CustomStatus`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CustomStatus</returns>
        public CustomStatus GetCustomStatus()
        {
            return (CustomStatus)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NewUsers207ResponseInner {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, NewUsers207ResponseInner.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of NewUsers207ResponseInner
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of NewUsers207ResponseInner</returns>
        public static NewUsers207ResponseInner FromJson(string jsonString)
        {
            NewUsers207ResponseInner newNewUsers207ResponseInner = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newNewUsers207ResponseInner;
            }

            try
            {
                newNewUsers207ResponseInner = new NewUsers207ResponseInner(JsonConvert.DeserializeObject<CustomStatus>(jsonString, NewUsers207ResponseInner.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newNewUsers207ResponseInner;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CustomStatus: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newNewUsers207ResponseInner = new NewUsers207ResponseInner(JsonConvert.DeserializeObject<UserModel>(jsonString, NewUsers207ResponseInner.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newNewUsers207ResponseInner;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into UserModel: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for NewUsers207ResponseInner
    /// </summary>
    public class NewUsers207ResponseInnerJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(NewUsers207ResponseInner).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return NewUsers207ResponseInner.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return NewUsers207ResponseInner.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
