/*
 * Criativei API
 *
 * API responsible for managing the distribution of images in their folders 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: agoisrj@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using criativei_server.Model;
using criativei_server.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace criativei_server.Test.Model
{
    /// <summary>
    ///  Class for testing AuditInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuditInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuditInfo
        //private AuditInfo instance;

        public AuditInfoTests()
        {
            // TODO uncomment below to create an instance of AuditInfo
            //instance = new AuditInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuditInfo
        /// </summary>
        [Fact]
        public void AuditInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuditInfo
            //Assert.IsType<AuditInfo>(instance);
        }

        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }

        /// <summary>
        /// Test the property 'UpdatedBy'
        /// </summary>
        [Fact]
        public void UpdatedByTest()
        {
            // TODO unit test for the property 'UpdatedBy'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
