/*
 * Criativei API
 *
 * API responsible for managing the distribution of images in their folders 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: agoisrj@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using criativei_server.Model;
using criativei_server.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace criativei_server.Test.Model
{
    /// <summary>
    ///  Class for testing NewUsers417ResponseInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewUsers417ResponseInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewUsers417ResponseInner
        //private NewUsers417ResponseInner instance;

        public NewUsers417ResponseInnerTests()
        {
            // TODO uncomment below to create an instance of NewUsers417ResponseInner
            //instance = new NewUsers417ResponseInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewUsers417ResponseInner
        /// </summary>
        [Fact]
        public void NewUsers417ResponseInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewUsers417ResponseInner
            //Assert.IsType<NewUsers417ResponseInner>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
