/*
 * Criativei API
 *
 * API responsible for managing the distribution of images in their folders 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: agoisrj@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using criativei_server.Model;
using criativei_server.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace criativei_server.Test.Model
{
    /// <summary>
    ///  Class for testing PageMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PageMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PageMetadata
        //private PageMetadata instance;

        public PageMetadataTests()
        {
            // TODO uncomment below to create an instance of PageMetadata
            //instance = new PageMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PageMetadata
        /// </summary>
        [Fact]
        public void PageMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" PageMetadata
            //Assert.IsType<PageMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'TotalElements'
        /// </summary>
        [Fact]
        public void TotalElementsTest()
        {
            // TODO unit test for the property 'TotalElements'
        }

        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Fact]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }

        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }

        /// <summary>
        /// Test the property 'HasNext'
        /// </summary>
        [Fact]
        public void HasNextTest()
        {
            // TODO unit test for the property 'HasNext'
        }

        /// <summary>
        /// Test the property 'HasPrev'
        /// </summary>
        [Fact]
        public void HasPrevTest()
        {
            // TODO unit test for the property 'HasPrev'
        }

        /// <summary>
        /// Test the property 'FirstPage'
        /// </summary>
        [Fact]
        public void FirstPageTest()
        {
            // TODO unit test for the property 'FirstPage'
        }

        /// <summary>
        /// Test the property 'LastPage'
        /// </summary>
        [Fact]
        public void LastPageTest()
        {
            // TODO unit test for the property 'LastPage'
        }
    }
}
